export enum TokenType {
  Function = 'Function',
  Return = 'Return',
  Let = 'Let',
  IntegerLiteral = 'IntegerLiteral',
  LeftBracket = 'LeftBracket',
  RightBracket = 'RightBracket',
  LeftParen = 'LeftParen',
  RightParen = 'RightParen',
  LeftCurly = 'LeftCurly',
  RightCurly = 'RightCurly',
  Space = 'Space',
  Newline = 'Newline',
  Identifier = 'Identifier',
  StringLiteral = 'StringLiteral',
  Comma = 'Comma',
  Semicolon = 'Semicolon',
  Assign = 'Assign',
  Unknown = 'Unknown',
  Plus = 'Plus',
  Minus = 'Minus',
  Star = 'Star',
  Slash = 'Slash',
  If = 'If',
  Else = 'Else',
  ElseIf = 'ElseIf',
  GreaterThan = 'GreaterThan',
  LessThan = 'LessThan',
  GreaterThanEqual = 'GreaterThanEqual',
  LessThanEqual = 'LessThanEqual',
  Equal = 'Equal',
  NotEqual = 'NotEqual',
  For = 'For',
  PlusPlus = 'PlusPlus',
  MinusMinus = 'MinusMinus',
  While = 'While',
  Continue = 'Continue',
  Break = 'Break',
  And = 'And',
  Or = 'Or',
  SingleLineComment = 'SingleLineComment',
  MultiLineCommentStart = 'MultiLineCommentStart',
  MultiLineCommentEnd = 'MultiLineCommentEnd',
}

const TOKEN_TYPE_MAP = new Map<string, TokenType>([
  ['fn', TokenType.Function],
  ['return', TokenType.Return],
  ['let', TokenType.Let],
  ['if', TokenType.If],
  ['else', TokenType.Else],
  ['elseif', TokenType.ElseIf],
  ['for', TokenType.For],
  ['while', TokenType.While],
  ['continue', TokenType.Continue],
  ['break', TokenType.Break],
  //
  ['(', TokenType.LeftParen],
  [')', TokenType.RightParen],
  ['[', TokenType.LeftBracket],
  [']', TokenType.RightBracket],
  ['{', TokenType.LeftCurly],
  ['}', TokenType.RightCurly],
  [',', TokenType.Comma],
  [';', TokenType.Semicolon],
  ['=', TokenType.Assign],
  ['+', TokenType.Plus],
  ['-', TokenType.Minus],
  ['*', TokenType.Star],
  ['/', TokenType.Slash],
  ['>', TokenType.GreaterThan],
  ['<', TokenType.LessThan],
  ['\n', TokenType.Newline],
])

export const DOUBLE_CHAR_TOKEN_TYPE_MAP = new Map<string, TokenType>([
  ['>=', TokenType.GreaterThanEqual],
  ['<=', TokenType.LessThanEqual],
  ['==', TokenType.Equal],
  ['!=', TokenType.NotEqual],
  ['++', TokenType.PlusPlus],
  ['--', TokenType.MinusMinus],
  ['&&', TokenType.And],
  ['||', TokenType.Or],
  ['//', TokenType.SingleLineComment],
  ['/*', TokenType.MultiLineCommentStart],
  ['*/', TokenType.MultiLineCommentEnd],
])

export function tokenTypeFromString(str: string): TokenType {
  return TOKEN_TYPE_MAP.get(str) ?? TokenType.Unknown
}
